################################
## Input and output options
################################
INPUT: SAC_SESAME_M2.1     # Folder containing input SAC files. Default is current folder <.>
# OUTPUT: /path/to/output/files   # Folder where output files will be saved. Default is current folder <.>

################################
## Processing options
################################
Twindow: 10    # Duration, of the analysis window, in seconds. Default is <30>
MaxWindows: 40 # Maximum number of time windows to be analyzed. Set <0> for largest possible. Default is <0>
Fmin: 2      # Smallest frequency to analyze, in Hertz. Default is <1/Twindow>
Fmax: 14       # Largest frequency to analyze, in Hertz. Default is <0.5/Ts>
Fspacing: lin  # Linear <lin> or logarithmic <log> frequency spacing. Default is <lin>
Fnum: 0       # Number of frequencies, between Fmin and Fmax, to be analyzed. Default is <50>

MaxWaves: 3               # Number of waves to be modeled for each time window at a given frequency. Default is <1>
ModelRayleighWaves: true  # Boolean indicating whether to model or not Rayleigh waves. Default is <true>
ModelLoveWaves: true      # Boolean indicating whether to model or not Love waves. Default is <true>
ModelNoise: false          # Boolean indicating whether to allow or not a window without Rayleigh and Love waves. Default is <true>

