################################
## This is an example configuration file to be used with WaveDec
##

################################
## Input and output options
################################
INPUT: /path/to/input/files     # Folder containing input SAC files. Default is current folder <.>
OUTPUT: /path/to/output/files   # Folder where output files will be saved. Default is current folder <.>

################################
## Processing options
################################
Twindow: 25    # Duration, of the analysis window, in seconds. Default is <25>
MaxWindows: 50 # Maximum number of time windows to be analyzed. Set <0> for largest possible. Default is <0>
Fmin: 0.5      # Smallest frequency to analyze, in Hertz. Default is <10/Twindow>
Fmax: 15       # Largest frequency to analyze, in Hertz. Default is <min(20, 0.5/Ts)>
Fspacing: lin  # Linear <lin> or logarithmic <log> frequency spacing. Default is <lin>
Fnum: 50       # Number of frequencies, between Fmin and Fmax, to be analyzed.
               # Default is <50>. Set Fnum: 0 to model all DFT frequencies.
Vmin: 50       # Smallest velocity considered in m/s. May speed up computation. Default is <50>

MaxWaves: 5               # Maximum number of waves to be modeled for each time window at a given frequency. Default is <3>
ModelRayleighWaves: true  # Boolean indicating whether to model or not Rayleigh waves. Default is <true>
ModelLoveWaves: true      # Boolean indicating whether to model or not Love waves. Default is <true>
ModelNoise: true          # Boolean indicating whether to allow or not a window without Rayleigh and Love waves. Default is <true>

################################
## More processing options (less used)
################################
# Tstart: 10                # Ignore the initial Tstart seconds of the recording. Default is <0>.
# Kmax: 0.05                # The largest wavenumber to analyze, in 1/m. Default is inferred from array geometry.
# Kstep: 1e-3               # Step size for grid search along wavenumber axis, in 1/m. Default is inferred from array geometry.
# Estep: 0.1                # Step size for grid search along ellipticity angle axis, in rad. Default is <pi/90>.
# Ts: 0.01                  # Sampling time in seconds. This option will override what is found in the SAC headers.
# Gamma: 0.2                # Controls model complexity. (0 for pure ML, 1 for BIC, other values for intermediate strategies). Default is <1>
# ModelVerticalWaves: false # Boolean indicating whether to model or not Vertical-component-only waves. Default is <false>
                            # If ModelVerticalWaves = true, it will be forced ModelRayleighWaves = ModelLoveWaves = false
# MaxIterations: 5          # The maximum number of iterations for iterative wave estimation. Default is <10>

## End of ExampleConfig.yaml

