################################
## This is an example configuration file to be used with WaveDec
##

################################
## Input and output options
################################

INPUT: ./SAC_ZurichAirport_Active_Shot01
OUTPUT: Active_Shot01

################################
## Processing options
################################

SourcePosition : [685128.025,257495.474]
ShotDuration: 0.8
ShotStarts: [2.2, 5.0, 18.1, 25.6, 32.3, 39.9, 46.9, 54.3, 60.3, 65.0, 69.3, 73.9]

ModelCircularVerticalWaves: false
ModelCircularRayleighWaves: true
ModelNoise: true

Fmin : 0
Fmax : 60
Fnum : 61
Gamma : 0.1
MaxWaves : 5
Kmax : 0.18


